[pytest]
python_files = test_*.py
python_classes = Test*
python_functions = test_*

testpaths = tests

addopts =
    -v
    --html=reports/html/report.html
    --self-contained-html

log_cli = true
log_cli_level = INFO

markers = 
    smoke: Smoke tests
    regression: Regression tests
    integration: Integration tests
    e2e: End-to-End tests